# Generated by Django 4.2.6 on 2023-10-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTiffinService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiffin_service_name', models.CharField(max_length=100)),
                ('tiffin_service_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user_or_service_address')),
                ('tiffin_service_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorApp.vendorprofile')),
            ],
        ),
    ]
