# Generated by Django 4.2.6 on 2023-10-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_or_service_address',
            name='address_type',
            field=models.CharField(choices=[('vendor_address', 'Vendor Address'), ('user_address', 'User Address')], default='user_address', max_length=20),
        ),
    ]
